services:
  backend:
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    container_name: eliteshop-backend
    expose:
      - "8080"
    networks:
      - eliteshopcolombiabackend_default
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped

networks:
  eliteshopcolombiabackend_default:
    external: true
